### ISSUE TITLE
NaNs with ERC (Equal Risk Contribution)

### ISSUE THREAD

**Issue by shimikano** [lequant40/portfolio_allocation_js#3] opened 2019-03-27 16:40 UTC
Hello

Thanks a lot for this very cool library :)

I came across some NaN results while experimenting with the ERC algorithm. A Google Sheet with a specific test case can be found here:

https://docs.google.com/spreadsheets/d/1WNw4GLkoyOmC0Qjefga6N_imQejEIOtC_OjMXGWJkF0/edit?usp=sharing

I don't know whether this is supposed to happen, so please excuse this if it's a beginner's mistake.

Anyway, I thought I'd bring this to your attention.

Thanks again and best regards

**Comment by lequant40** [comment] 2019-03-27 18:43
Thanks a lot, I will have a look as soon as I find the time.

NB: I can think of NaNs happening in case the covariance matrix is not (semi) positive definite, but I would expect the algorithm to throw at some point instead of outputing NaNs, so, I am definitely intrigued :-) !

**Comment by shimikano** [comment] 2019-03-28 07:38
Thanks for your reply!

I thought so too about the precondition of the covariance matrix.
While debugging, it seemed that the NaNs happened [here](https://github.com/lequant40/portfolio_allocation_js/blob/v0.0.6/lib/allocation/risk-budgeting.js#L127).

**Comment by lequant40** [comment] 2019-03-29 15:39
I confirm the issue is related to the covariance matrix being semi-definite positive (i.e., determinant equal to 0).

In this case, it might happen that the variance is (numerically) negative zero (e.g. -0,000000000001), from which it is not possible to compute a volatility.

I added a proper management of this specific case on my local computer (more tricky than it seems due to the convergence condition of the algorithm which needs to be slightly amended), and it is now working OK on your example.

Commit will follow with non-regression tests, and will be included in the next release 0.0.7.

Thanks again for reporting.

**Comment by shimikano** [comment] 2019-03-29 16:28
Thank you very much, looking forward to the new release :)

**Comment by lequant40** [comment] 2019-05-25 14:13
Solved with today's release of v0.0.7 of the library.

**Closed by lequant40** 2019-05-25 14:13 UTC
